// Authentication Action Types
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const CHECK_AUTH = 'CHECK_AUTH';

// Order Action Types
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAILURE = 'FETCH_ORDER_FAILURE';

export const CREATE_ORDER_START = 'CREATE_ORDER_START';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';

export const UPDATE_ORDER_START = 'UPDATE_ORDER_START';
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS';
export const UPDATE_ORDER_FAILURE = 'UPDATE_ORDER_FAILURE';

export const DELETE_ORDER_START = 'DELETE_ORDER_START';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';

export const ADVANCE_ORDER_START = 'ADVANCE_ORDER_START';
export const ADVANCE_ORDER_SUCCESS = 'ADVANCE_ORDER_SUCCESS';
export const ADVANCE_ORDER_FAILURE = 'ADVANCE_ORDER_FAILURE';

export const FETCH_ORDER_STATS_START = 'FETCH_ORDER_STATS_START';
export const FETCH_ORDER_STATS_SUCCESS = 'FETCH_ORDER_STATS_SUCCESS';
export const FETCH_ORDER_STATS_FAILURE = 'FETCH_ORDER_STATS_FAILURE';

// Customer Action Types
export const FETCH_CUSTOMERS_START = 'FETCH_CUSTOMERS_START';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';
export const FETCH_CUSTOMERS_FAILURE = 'FETCH_CUSTOMERS_FAILURE';

export const CREATE_CUSTOMER_START = 'CREATE_CUSTOMER_START';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAILURE = 'CREATE_CUSTOMER_FAILURE';

export const DELETE_CUSTOMER_START = 'DELETE_CUSTOMER_START';
export const DELETE_CUSTOMER_SUCCESS = 'DELETE_CUSTOMER_SUCCESS';
export const DELETE_CUSTOMER_FAILURE = 'DELETE_CUSTOMER_FAILURE';

// Customer Authentication Action Types
export const CUSTOMER_LOGIN_START = 'CUSTOMER_LOGIN_START';
export const CUSTOMER_LOGIN_SUCCESS = 'CUSTOMER_LOGIN_SUCCESS';
export const CUSTOMER_LOGIN_FAILURE = 'CUSTOMER_LOGIN_FAILURE';
export const CUSTOMER_LOGOUT = 'CUSTOMER_LOGOUT';
export const CUSTOMER_CLEAR_AUTH_ERROR = 'CUSTOMER_CLEAR_AUTH_ERROR';
export const CUSTOMER_CHECK_AUTH = 'CUSTOMER_CHECK_AUTH';
export const CUSTOMER_UPDATE_PROFILE_START = 'CUSTOMER_UPDATE_PROFILE_START';
export const CUSTOMER_UPDATE_PROFILE_SUCCESS = 'CUSTOMER_UPDATE_PROFILE_SUCCESS';
export const CUSTOMER_UPDATE_PROFILE_FAILURE = 'CUSTOMER_UPDATE_PROFILE_FAILURE'; 